In [1]:
from __future__ import print_function, division

import numpy as np

from skcriteria import ahp
from skcriteria.common import norm

## Data

In [2]:
vs_criteria = ahp.t([
    [1.],            # location
    [1/2., 1.],      # area
    [1/8., 1/6., 1.] # price
])

alt_vs_alt_by_crit = [
    ahp.t([[1], [8, 1], [6, 1/2, 1]]),   # location
    ahp.t([[1], [1/7, 1], [1/5, 3, 1]]), # area
    ahp.t([[1], [1/7, 1], [1/3, 3, 1]]), # price
]

print("Criteria Vs. Criteria:\n", vs_criteria, "\n")
print("Alternative Vs. Alternative By Location:\n", alt_vs_alt_by_crit[0], "\n")
print("Alternative Vs. Alternative By Area:\n", alt_vs_alt_by_crit[1], "\n")
print("Alternative Vs. Alternative By Price:\n", alt_vs_alt_by_crit[2], "\n")

Criteria Vs. Criteria:
 [[ 1.          2.          8.        ]
 [ 0.5         1.          6.        ]
 [ 0.125       0.16666667  1.        ]] 

Alternative Vs. Alternative By Location:
 [[ 1.          0.125       0.16666667]
 [ 8.          1.          2.        ]
 [ 6.          0.5         1.        ]] 

Alternative Vs. Alternative By Area:
 [[ 1.          7.          5.        ]
 [ 0.14285714  1.          0.33333333]
 [ 0.2         3.          1.        ]] 

Alternative Vs. Alternative By Price:
 [[ 1.          7.          3.        ]
 [ 0.14285714  1.          0.33333333]
 [ 0.33333333  3.          1.        ]] 



In [22]:
result = ahp.ahp(vs_criteria, alt_vs_alt_by_crit)

ranked, points, crit_ci, avabc_ci, crit_cr, avabc_cr = result
print("Rank:", ranked)
print("Points:", points)
print("Criteria Vs. Criteria CR:", crit_cr, "[> 0.1 - Consistent]" if crit_cr < 0.1 else "[< 0.1 - Inconsistent]")
print("Alternative Vs. Alternative By Location CR:", avabc_ir[0], "[< 0.1 - Consistent]" if avabc_cr[0] < 0.1 else "[> 0.1 - Inconsistent]")
print("Alternative Vs. Alternative By Area CR:", avabc_ir[1], "[< 0.1 - Consistent]" if avabc_cr[1] < 0.1 else "[> 0.1 - Inconsistent]")
print("Alternative Vs. Alternative By Price CR:", avabc_ir[2], "[< 0.1 - Consistent]" if avabc_cr[2] < 0.1 else "[> 0.1 - Inconsistent]")

Rank: [2 1 3]
Points: [ 0.32938398  0.38635231  0.28426372]
Criteria Vs. Criteria CR: 0.0176324296565 [> 0.1 - Consistent]
Alternative Vs. Alternative By Location CR: 0.00916920780479 [< 0.1 - Consistent]
Alternative Vs. Alternative By Area CR: 0.0329093351825 [< 0.1 - Consistent]
Alternative Vs. Alternative By Price CR: 0.00351519171738 [< 0.1 - Consistent]
