# Array Normalization And Ratios

In [1]:
import numpy as np
from skcriteria.common import norm

In [2]:
mtx = [[1, 2], [3, 4]]
mtx

[[1, 2], [3, 4]]

## Normalization by The sumatory of the array

In [3]:
%%latex 
\begin{align}
\overline{X}_{ij} = \frac{X_{ij}}{\sum\limits_{j=1}^m X_{ij}}
\end{align}

<IPython.core.display.Latex object>

In [4]:
norm.sum(mtx) # ratios with the sumatory of the array

array([[ 0.1,  0.2],
       [ 0.3,  0.4]])

In [5]:
norm.sum(mtx, axis=0) # ratios with the sumatory of the array by column

array([[ 0.25      ,  0.33333333],
       [ 0.75      ,  0.66666667]])

In [6]:
norm.sum(mtx, axis=1) # ratios with the sumatory of the array by row

array([[ 0.33333333,  0.66666667],
       [ 0.42857143,  0.57142857]])

## Normalization by the Max Value of the array

In [7]:
%%latex 
\begin{align}
\overline{X}_{ij} = \frac{X_{ij}}{\max_{X_{ij}}}
\end{align}

<IPython.core.display.Latex object>

In [8]:
norm.max(mtx) # ratios with the max value of the array

array([[ 0.25,  0.5 ],
       [ 0.75,  1.  ]])

In [9]:
norm.max(mtx, axis=0) # ratios with the max value of the array by column

array([[ 0.33333333,  0.5       ],
       [ 1.        ,  1.        ]])

In [10]:
norm.max(mtx, axis=1) # ratios with the max value of the array by row

array([[ 0.5 ,  1.  ],
       [ 0.75,  1.  ]])

## Normalization by Vector

In [11]:
%%latex 
\begin{align}
 \overline{X}_{ij} = \frac{X_{ij}}{\sqrt{\sum\limits_{j=1}^m X_{ij}^{2}}}
\end{align}

<IPython.core.display.Latex object>

In [12]:
norm.vector(mtx) # ratios with the vector value of the array

array([[ 0.18257419,  0.36514837],
       [ 0.54772256,  0.73029674]])

In [13]:
norm.vector(mtx, axis=0) # ratios with the vector value of the array by column

array([[ 0.31622777,  0.4472136 ],
       [ 0.9486833 ,  0.89442719]])

In [14]:
norm.vector(mtx, axis=1) # ratios with the vector value of the array by row

array([[ 0.4472136 ,  0.4       ],
       [ 1.34164079,  0.8       ]])

##Push Negatives

In [15]:
%%latex 
\begin{align}
\overline{X}_{ij} =
\begin{cases}
    X_{ij} + min_{X_{ij}} & \text{if } X_{ij} < 0\\
    X_{ij}          & \text{otherwise}
\end{cases}
\end{align}

<IPython.core.display.Latex object>

In [16]:
mtx_lt0 = [[-1, 2], [3, 4]]

In [17]:
norm.push_negatives(mtx) # array without negatives dont be afected

array([[1, 2],
       [3, 4]])

In [18]:
norm.push_negatives(mtx_lt0) # all the array is incremented by 1 to eliminate the negative

array([[0, 3],
       [4, 5]])

In [19]:
norm.push_negatives(mtx_lt0, axis=0) # by column only the first one is afected

array([[0, 2],
       [4, 4]])

In [20]:
norm.push_negatives(mtx_lt0, axis=1) # by row only the first row is afected

array([[0, 3],
       [3, 4]])

##Epsilon

In [21]:
%%latex 
\begin{align}
\overline{X}_{ij} = X_{ij} + \epsilon
\end{align}

<IPython.core.display.Latex object>

In [22]:
mtx_w0 = [[0,1], [2,3]]

In [23]:
norm.eps(mtx) # not afected

array([[1, 2],
       [3, 4]])

In [24]:
norm.eps(mtx_w0) # added a value 0,00000000000000002, ans id only perceptible in tue 0

array([[  2.22044605e-16,   1.00000000e+00],
       [  2.00000000e+00,   3.00000000e+00]])